/* FLOA — one script, assembled from every component behaviour.
   Generated by build.mjs — edit the files under src/, not this one. */

window.FLOA = { config: {
  "whatsapp": {
    "number": "972587078708",
    "greeting": "היי, הגעתי דרך האתר של FLOA ואשמח שתעזרו לי"
  },
  "formError": "השליחה נכשלה. אפשר לנסות שוב או לכתוב לי בוואטסאפ",
  "systemLabels": [
    "אתרים ודפי נחיתה",
    "אפליקציות ומערכות",
    "WhatsApp, לידים ומכירות",
    "תשלומים וגבייה",
    "אוטומציות, נתונים ודוחות"
  ]
} };

/* ======================================================================
   lib/core.client.js
   ====================================================================== */
/* window.FLOA.config is written above this line by build.mjs, straight from
   src/content/site.js — the browser and the generator read the same source. */
(function () {
  "use strict";

  /* fires only if a GA/GTM container already exists; never loads one */
  window.FLOA.track = function (name) {
    try {
      if (window.dataLayer && typeof window.dataLayer.push === "function") window.dataLayer.push({ event: name });
      else if (typeof window.gtag === "function") window.gtag("event", name);
    } catch (e) { /* analytics must never break the page */ }
  };

  document.querySelectorAll("[data-analytics]").forEach(function (el) {
    el.addEventListener("click", function () { window.FLOA.track(el.getAttribute("data-analytics")); });
  });
})();

/* ======================================================================
   lib/reveal.client.js
   ====================================================================== */
/* Anything with .reveal fades up as it enters the viewport, once. */
(function () {
  "use strict";
  var items = document.querySelectorAll(".reveal");
  if (!items.length) return;

  var show = function (el) { el.classList.add("in-view"); };

  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches || !("IntersectionObserver" in window)) {
    items.forEach(show);
    return;
  }

  var io = new IntersectionObserver(function (entries) {
    entries.forEach(function (entry, i) {
      if (!entry.isIntersecting) return;
      setTimeout(function () { show(entry.target); }, Math.min(i * 60, 180));   // a stagger, not a queue
      io.unobserve(entry.target);
    });
  }, { rootMargin: "0px 0px -8% 0px", threshold: 0.12 });

  items.forEach(function (el) { io.observe(el); });
})();

/* ======================================================================
   lib/anchors.client.js
   ====================================================================== */
/* ==========================================================================
   In-page navigation.

   Native anchor jumps are unreliable here: the browser fixes the scroll
   destination at click time, then web fonts swap and lazy images resolve ABOVE
   the target, the page grows, and the landing drifts. So we compute the
   destination ourselves and re-check it once the page settles.

   Nothing is written to the URL — no #hash is ever appended.
   ========================================================================== */
(function () {
  "use strict";
  var GAP = 40;   // air left above a section's content after a jump

  /* where a section should come to rest: its first real content, GAP below the
     top of the viewport — not its border box, which would leave the section's
     whole top padding as dead space */
  function destinationFor(target) {
    var anchor = target.querySelector(".container > *") || target;
    var top = anchor.getBoundingClientRect().top + window.pageYOffset - GAP;
    return Math.max(0, Math.min(top, document.documentElement.scrollHeight - window.innerHeight));
  }

  function scrollToTarget(target) {
    var interrupted = false;
    var stop = function () { interrupted = true; };
    window.addEventListener("wheel", stop, { passive: true, once: true });
    window.addEventListener("touchstart", stop, { passive: true, once: true });

    window.scrollTo({
      top: destinationFor(target),
      behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth",
    });

    // the page may still be growing above the target (fonts, lazy images), so
    // re-measure after the smooth scroll settles and correct any drift
    [800, 1400, 2200].forEach(function (delay) {
      setTimeout(function () {
        if (interrupted) return;
        var want = destinationFor(target);
        if (Math.abs(window.pageYOffset - want) > 4) window.scrollTo({ top: want, behavior: "auto" });
      }, delay);
    });
  }

  document.querySelectorAll('a[href^="#"]').forEach(function (link) {
    var id = link.getAttribute("href");
    if (!id || id === "#") return;                 // WhatsApp links are rewritten elsewhere

    link.addEventListener("click", function (e) {
      var target = document.querySelector(id);
      if (!target) return;
      e.preventDefault();                          // keeps the hash out of the URL
      scrollToTarget(target);
    });
  });
})();

/* ======================================================================
   components/whatsapp-button/whatsapp-button.client.js
   ====================================================================== */
/* Every [data-whatsapp] element — button, hero CTA, footer link — gets its href
   written here, from the one number in site config. Nothing hardcodes wa.me. */
(function () {
  "use strict";
  var wa = window.FLOA.config.whatsapp;
  var href = wa.number
    ? "https://wa.me/" + wa.number + "?text=" + encodeURIComponent(wa.greeting)
    : "#contact";

  document.querySelectorAll("[data-whatsapp]").forEach(function (el) {
    el.setAttribute("href", href);
    if (wa.number) {
      el.setAttribute("target", "_blank");
      el.setAttribute("rel", "noopener");
    }
  });
})();

/* ======================================================================
   components/contact/contact.client.js
   ====================================================================== */
/* The contact form: validate, save the lead, and only then say "thank you". */
(function () {
  "use strict";
  var form = document.getElementById("contactForm");
  if (!form) return;

  var success = document.getElementById("formSuccess");
  var phone = document.getElementById("phone");
  var help = document.getElementById("help");
  var submitBtn = form.querySelector('button[type="submit"]');
  var controls = form.querySelectorAll("input, select, textarea");
  var errorText = window.FLOA.config.formError;

  /* Israeli mobile or landline, however it was typed */
  function validIL(value) {
    var p = (value || "").replace(/[^\d+]/g, "").replace(/^\+972/, "0").replace(/^972/, "0");
    return /^0(?:5\d{8}|[2-489]\d{7})$/.test(p);
  }

  // functional error line, created once and shown only on a real failure
  var errorEl = document.createElement("p");
  errorEl.className = "form-error";
  errorEl.setAttribute("role", "alert");
  errorEl.hidden = true;
  errorEl.textContent = errorText;
  form.parentNode.insertBefore(errorEl, form.nextSibling);

  /* keep the "how can we help" select greyed while it sits on the placeholder */
  if (help) {
    var refresh = function () { help.classList.toggle("is-empty", !help.value); };
    help.addEventListener("change", refresh);
    refresh();
  }

  /* Error styling is driven by .is-invalid, applied ONLY after a submit attempt.
     A CSS :invalid rule would paint every required field red while the form is
     still untouched. */
  controls.forEach(function (el) {
    ["input", "change"].forEach(function (evt) {
      el.addEventListener(evt, function () { el.classList.remove("is-invalid"); });
    });
  });
  if (phone) phone.addEventListener("input", function () { phone.setCustomValidity(""); });

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    errorEl.hidden = true;

    if (phone) phone.setCustomValidity(validIL(phone.value) ? "" : "אנא הזינו מספר טלפון ישראלי תקין");

    if (!form.checkValidity()) {
      controls.forEach(function (el) { el.classList.toggle("is-invalid", !el.checkValidity()); });
      form.reportValidity();
      return;
    }
    if (success) success.hidden = true;
    window.FLOA.track("contact_form_submit");

    var data = new FormData(form);
    var lead = {};
    ["name", "phone", "business", "help", "improve"].forEach(function (key) {
      lead[key] = (data.get(key) || "").toString().trim();
    });

    if (submitBtn) submitBtn.disabled = true;

    var save = typeof window.floaSaveLead === "function"
      ? window.floaSaveLead(lead)
      : Promise.reject(new Error("lead storage unavailable"));

    Promise.resolve(save).then(function () {
      window.FLOA.track("contact_form_success");     // success ONLY after the send actually succeeded
      form.reset();
      if (help) help.classList.add("is-empty");
      if (submitBtn) submitBtn.disabled = false;
      if (success) {
        success.hidden = false;
        success.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }).catch(function (err) {
      console.warn("FLOA: lead not sent —", err && err.message);
      if (submitBtn) submitBtn.disabled = false;
      errorEl.hidden = false;
      errorEl.scrollIntoView({ behavior: "smooth", block: "center" });
    });
  });
})();

/* ======================================================================
   components/hero-system/hero-system.client.js
   ====================================================================== */
/* ==========================================================================
   The hero system, alive.

   Each solution lights in turn and sends a pulse down its wire into the hub.
   Pulses are positioned with getPointAtLength() along the REAL <path> geometry,
   so a wire can be re-routed in the SVG and the pulse still follows it exactly —
   no duplicated coordinates to keep in sync.
   ========================================================================== */
(function () {
  "use strict";
  var root = document.getElementById("heroSystem");
  if (!root) return;

  var LABELS = window.FLOA.config.systemLabels;
  var STEP = 2600;            // ms a solution stays lit
  var TRAVEL = 1400;          // ms for a pulse to run the wire

  var nodes = root.querySelectorAll(".node");
  var wires = root.querySelectorAll(".wires path");
  var pulses = root.querySelectorAll(".pulse");
  var caption = document.getElementById("systemCaption");
  var textEl = caption ? caption.querySelector(".system-caption-text") : null;

  var lengths = Array.prototype.map.call(wires, function (w) { return w.getTotalLength(); });
  var current = 0;
  var timer = null;
  var raf = null;
  var running = false;

  /* A page may "feature" one node: it stays lit and forward while the rest keep
     pulsing, so the visitor sees THEIR solution at the centre — still wired into
     the one FLOA system. No attribute (the homepage) → nothing is pinned. */
  var feature = parseInt(root.getAttribute("data-feature"), 10);
  if (isNaN(feature)) feature = -1;
  if (feature >= 0 && nodes[feature]) nodes[feature].classList.add("is-feature");

  function placePulse(index, progress) {
    var wire = wires[index];
    var pulse = pulses[index];
    if (!wire || !pulse) return;
    var pt = wire.getPointAtLength(lengths[index] * progress);
    pulse.setAttribute("cx", pt.x);
    pulse.setAttribute("cy", pt.y);
  }

  /* light one solution: its card, its wire, and its caption */
  function light(index) {
    nodes.forEach(function (node, n) { node.classList.toggle("is-lit", n === index || n === feature); });
    wires.forEach(function (wire, w) { wire.classList.toggle("is-lit", w === index || w === feature); });

    if (feature >= 0 || !textEl) return;     // a featured caption never swaps away
    caption.classList.add("is-swapping");
    setTimeout(function () {
      textEl.textContent = LABELS[index] || "";
      caption.classList.remove("is-swapping");
    }, 350);
  }

  /* run one pulse from its card down into the hub */
  function sendPulse(index) {
    var pulse = pulses[index];
    if (!pulse) return;
    var start = null;
    pulse.classList.add("is-live");

    raf = requestAnimationFrame(function frame(now) {
      if (!running) return;
      if (start === null) start = now;

      var p = (now - start) / TRAVEL;
      if (p >= 1) {
        placePulse(index, 1);
        pulse.classList.remove("is-live");
        return;
      }
      // ease-in-out: the packet gathers speed, then settles into the hub
      placePulse(index, p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2);
      raf = requestAnimationFrame(frame);
    });
  }

  function advance() {
    light(current);
    sendPulse(current);
    current = (current + 1) % LABELS.length;
  }

  function start() {
    if (running) return;
    running = true;
    advance();
    timer = setInterval(advance, STEP);
  }

  function stop() {
    running = false;
    clearInterval(timer);
    if (raf) cancelAnimationFrame(raf);
    timer = raf = null;
  }

  /* reduced motion: show the finished state — everything connected, nothing moves */
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
    nodes.forEach(function (n) { n.classList.add("is-lit"); });
    wires.forEach(function (w) { w.classList.add("is-lit"); });
    if (textEl && !textEl.textContent) textEl.textContent = "הכול מחובר למערכת אחת";
    return;
  }

  if (feature >= 0) current = feature;      // open the cycle on the featured solution
  else if (textEl) textEl.textContent = LABELS[0];

  // only animate while the hero is actually on screen
  if ("IntersectionObserver" in window) {
    new IntersectionObserver(function (entries) {
      if (entries[0].isIntersecting) start(); else stop();
    }, { threshold: 0 }).observe(root);
  } else {
    start();
  }
})();
