/* FLOA — one script, assembled from every component behaviour.
   Generated by build.mjs — edit the files under src/, not this one. */

window.FLOA = { config: {
  "whatsapp": {
    "number": "972587078708",
    "greeting": "היי, הגעתי דרך אתר FLOA ואשמח לשיחה קצרה"
  },
  "leadEndpoint": "https://floa-lead.floa-il.workers.dev/lead",
  "formError": "לא הצלחנו לשלוח את הפרטים. אפשר לנסות שוב או לפנות אלינו ב־WhatsApp",
  "systemLabels": [
    "אתרים ודפי נחיתה",
    "אפליקציות ומערכות",
    "WhatsApp והתראות",
    "טפסים ותשלומים",
    "אוטומציות, נתונים ודוחות"
  ]
} };

/* ======================================================================
   lib/core.client.js
   ====================================================================== */
/* window.FLOA.config is written above this line by build.mjs, straight from
   src/content/site.js — the browser and the generator read the same source. */
(function () {
  "use strict";

  /* fires only if a GA/GTM container already exists; never loads one */
  window.FLOA.track = function (name) {
    try {
      if (window.dataLayer && typeof window.dataLayer.push === "function") window.dataLayer.push({ event: name });
      else if (typeof window.gtag === "function") window.gtag("event", name);
    } catch (e) { /* analytics must never break the page */ }
  };

  document.querySelectorAll("[data-analytics]").forEach(function (el) {
    el.addEventListener("click", function () { window.FLOA.track(el.getAttribute("data-analytics")); });
  });
})();

/* ======================================================================
   lib/reveal.client.js
   ====================================================================== */
/* Anything with .reveal fades up as it enters the viewport, once. */
(function () {
  "use strict";
  var items = document.querySelectorAll(".reveal");
  if (!items.length) return;

  var show = function (el) { el.classList.add("in-view"); };

  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches || !("IntersectionObserver" in window)) {
    items.forEach(show);
    return;
  }

  var io = new IntersectionObserver(function (entries) {
    entries.forEach(function (entry, i) {
      if (!entry.isIntersecting) return;
      setTimeout(function () { show(entry.target); }, Math.min(i * 60, 180));   // a stagger, not a queue
      io.unobserve(entry.target);
    });
  }, { rootMargin: "0px 0px -8% 0px", threshold: 0.12 });

  items.forEach(function (el) { io.observe(el); });
})();

/* ======================================================================
   lib/anchors.client.js
   ====================================================================== */
/* ==========================================================================
   In-page navigation.

   Native anchor jumps are unreliable here: the browser fixes the scroll
   destination at click time, then web fonts swap and lazy images resolve ABOVE
   the target, the page grows, and the landing drifts. So we compute the
   destination ourselves and re-check it once the page settles.

   Nothing is written to the URL — no #hash is ever appended.
   ========================================================================== */
(function () {
  "use strict";
  var GAP = 40;   // air left above a section's content after a jump

  /* where a section should come to rest: its first real content, GAP below the
     top of the viewport — not its border box, which would leave the section's
     whole top padding as dead space */
  function destinationFor(target) {
    var anchor = target.querySelector(".container > *") || target;
    var top = anchor.getBoundingClientRect().top + window.pageYOffset - GAP;
    return Math.max(0, Math.min(top, document.documentElement.scrollHeight - window.innerHeight));
  }

  function scrollToTarget(target) {
    var interrupted = false;
    var stop = function () { interrupted = true; };
    window.addEventListener("wheel", stop, { passive: true, once: true });
    window.addEventListener("touchstart", stop, { passive: true, once: true });

    window.scrollTo({
      top: destinationFor(target),
      behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth",
    });

    // the page may still be growing above the target (fonts, lazy images), so
    // re-measure after the smooth scroll settles and correct any drift
    [800, 1400, 2200].forEach(function (delay) {
      setTimeout(function () {
        if (interrupted) return;
        var want = destinationFor(target);
        if (Math.abs(window.pageYOffset - want) > 4) window.scrollTo({ top: want, behavior: "auto" });
      }, delay);
    });
  }

  document.querySelectorAll('a[href^="#"]').forEach(function (link) {
    var id = link.getAttribute("href");
    if (!id || id === "#") return;                 // WhatsApp links are rewritten elsewhere

    link.addEventListener("click", function (e) {
      var target = document.querySelector(id);
      if (!target) return;
      e.preventDefault();                          // keeps the hash out of the URL
      scrollToTarget(target);
    });
  });
})();

/* ======================================================================
   components/whatsapp-button/whatsapp-button.client.js
   ====================================================================== */
/* Every [data-whatsapp] element on the page — the hero CTA, the mid-page band,
   the sticky dock, the footer link — gets its href written here, from the ONE
   number in site config and the ONE message the page carries. Nothing anywhere
   else builds a wa.me URL, so every WhatsApp button on a page is guaranteed to
   open the same conversation.

   The message is per-page: the build writes it onto <body data-wa-text>, so the
   automations page opens WhatsApp already talking about automations. The shared
   greeting is the fallback for a page that sets none (the legal pages).

   A phone hands off to the WhatsApp app via wa.me. A desktop has no app to hand
   off to, so it opens WhatsApp Web directly rather than bouncing through the
   wa.me interstitial. */
(function () {
  "use strict";
  var wa = window.FLOA.config.whatsapp;
  var targets = document.querySelectorAll("[data-whatsapp]");
  if (!targets.length || !wa.number) return;

  var text = encodeURIComponent(document.body.getAttribute("data-wa-text") || wa.greeting);

  var mobile = (window.matchMedia && window.matchMedia("(max-width: 768px)").matches) ||
               /Mobi|Android|iPhone|iPad|iPod/i.test(navigator.userAgent);

  var href = mobile
    ? "https://wa.me/" + wa.number + "?text=" + text
    : "https://web.whatsapp.com/send?phone=" + wa.number + "&text=" + text;

  targets.forEach(function (el) {
    el.setAttribute("href", href);
    el.setAttribute("target", "_blank");
    el.setAttribute("rel", "noopener");
  });
})();

/* ======================================================================
   components/contact/contact.client.js
   ====================================================================== */
/* The contact form.

   Validate, POST the lead to the email API, and say "thank you" ONLY once the
   server has confirmed the email actually went out. Nothing is stored in the
   browser, nothing is written to Firebase, and a successful send never opens
   WhatsApp — the visitor asked to be called back, so we call back.

   On failure the fields are deliberately left ALONE: the visitor gets the error
   under the button and can press it again without retyping anything. */
(function () {
  "use strict";
  var form = document.getElementById("contactForm");
  if (!form) return;

  var success = document.getElementById("formSuccess");
  var name = document.getElementById("name");
  var phone = document.getElementById("phone");
  var submitBtn = form.querySelector('button[type="submit"]');
  var fields = form.querySelectorAll("input:not([type=hidden]):not(#company)");

  var endpoint = window.FLOA.config.leadEndpoint;
  var sending = false;              // guards against a double send
  var lastSentAt = 0;               // and against hammering the button

  /* an Israeli mobile or landline, however it was typed */
  function validPhone(value) {
    var p = (value || "").replace(/[^\d+]/g, "").replace(/^\+972/, "0").replace(/^972/, "0");
    return /^0(?:5\d{8}|[2-489]\d{7})$/.test(p);
  }
  function validName(value) {
    return (value || "").trim().length >= 2;
  }

  /* the error line, created once and shown only on a real failure — directly
     under the button, which is where the visitor is looking when it fails */
  var errorEl = document.createElement("p");
  errorEl.className = "form-error";
  errorEl.setAttribute("role", "alert");
  errorEl.hidden = true;
  errorEl.textContent = window.FLOA.config.formError;
  form.parentNode.insertBefore(errorEl, form.nextSibling);

  /* Error styling is driven by .is-invalid and applied ONLY after a submit
     attempt. A CSS :invalid rule would paint both fields red while the form is
     still untouched. */
  fields.forEach(function (el) {
    ["input", "change"].forEach(function (evt) {
      el.addEventListener(evt, function () {
        el.classList.remove("is-invalid");
        el.setCustomValidity("");
      });
    });
  });

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    if (sending) return;
    if (Date.now() - lastSentAt < 5000) return;   // no repeat sends on a hot button

    errorEl.hidden = true;
    if (success) success.hidden = true;

    if (name) name.setCustomValidity(validName(name.value) ? "" : "אנא הזינו שם");
    if (phone) phone.setCustomValidity(validPhone(phone.value) ? "" : "אנא הזינו מספר טלפון ישראלי תקין");

    if (!form.checkValidity()) {
      fields.forEach(function (el) { el.classList.toggle("is-invalid", !el.checkValidity()); });
      form.reportValidity();
      return;
    }

    var data = new FormData(form);
    var lead = {
      name: (data.get("name") || "").toString().trim(),
      phone: (data.get("phone") || "").toString().trim(),
      page: (data.get("page") || "").toString(),
      company: (data.get("company") || "").toString(),   // the honeypot: server drops it if filled
      url: window.location.href,
    };

    sending = true;
    if (submitBtn) submitBtn.disabled = true;
    window.FLOA.track("contact_form_submit");

    fetch(endpoint, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(lead),
    }).then(function (res) {
      if (!res.ok) throw new Error("lead endpoint returned " + res.status);
      return res.json().catch(function () { return {}; });
    }).then(function (body) {
      /* the server confirms the email left; anything else is a failure, even a 200 */
      if (body && body.ok === false) throw new Error(body.error || "send failed");

      window.FLOA.track("contact_form_success");
      lastSentAt = Date.now();
      form.reset();                                  // cleared ONLY on success
      if (success) {
        success.hidden = false;
        success.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }).catch(function (err) {
      console.warn("FLOA: lead not sent —", err && err.message);
      errorEl.hidden = false;                        // fields keep what the visitor typed
      errorEl.scrollIntoView({ behavior: "smooth", block: "center" });
    }).then(function () {
      sending = false;
      if (submitBtn) submitBtn.disabled = false;
    });
  });
})();

/* ======================================================================
   components/faq/faq.client.js
   ====================================================================== */
/* One answer open at a time. <details> already does the opening, the keyboard and
   the announcing — all this adds is closing the others, so the list never grows
   into a wall of text. No-ops on a page with no accordion. */
(function () {
  "use strict";
  document.querySelectorAll("[data-faq]").forEach(function (group) {
    var items = group.querySelectorAll("details");
    items.forEach(function (item) {
      item.addEventListener("toggle", function () {
        if (!item.open) return;
        items.forEach(function (other) { if (other !== item) other.open = false; });
      });
    });
  });
})();

/* ======================================================================
   components/cta-dock/cta-dock.client.js
   ====================================================================== */
/* The sticky mobile CTA appears only after the visitor has scrolled past the
   hero, and disappears whenever the contact form is on screen — so it never
   covers the very ask it points at. No-ops when the dock isn't on the page. */
(function () {
  "use strict";
  var dock = document.querySelector("[data-cta-dock]");
  if (!dock) return;

  var hero = document.getElementById("hero");
  var contact = document.getElementById("contact");
  var pastHero = !hero;      // no hero → treat as already passed
  var atContact = false;

  function update() {
    var show = pastHero && !atContact;
    dock.classList.toggle("is-visible", show);
    document.body.classList.toggle("cta-dock-active", show);
  }

  if (!("IntersectionObserver" in window)) { pastHero = true; update(); return; }

  if (hero) {
    new IntersectionObserver(function (entries) {
      pastHero = !entries[0].isIntersecting;   // hero fully out of view
      update();
    }, { threshold: 0 }).observe(hero);
  }
  if (contact) {
    new IntersectionObserver(function (entries) {
      atContact = entries[0].isIntersecting;   // form is on screen
      update();
    }, { threshold: 0 }).observe(contact);
  }

  update();
})();

/* ======================================================================
   components/hero-system/hero-system.client.js
   ====================================================================== */
/* ==========================================================================
   The hero system, alive.

   Each solution lights in turn and sends a pulse down its wire into the hub.
   Pulses are positioned with getPointAtLength() along the REAL <path> geometry,
   so a wire can be re-routed in the SVG and the pulse still follows it exactly —
   no duplicated coordinates to keep in sync.
   ========================================================================== */
(function () {
  "use strict";
  var root = document.getElementById("heroSystem");
  if (!root) return;

  var LABELS = window.FLOA.config.systemLabels;
  var STEP = 2600;            // ms a solution stays lit
  var TRAVEL = 1400;          // ms for a pulse to run the wire

  var nodes = root.querySelectorAll(".node");
  var wires = root.querySelectorAll(".wires path");
  var pulses = root.querySelectorAll(".pulse");
  var caption = document.getElementById("systemCaption");
  var textEl = caption ? caption.querySelector(".system-caption-text") : null;

  var lengths = Array.prototype.map.call(wires, function (w) { return w.getTotalLength(); });
  var current = 0;
  var timer = null;
  var raf = null;
  var running = false;

  /* A page may "feature" one node: it stays lit and forward while the rest keep
     pulsing, so the visitor sees THEIR solution at the centre — still wired into
     the one FLOA system. No attribute (the homepage) → nothing is pinned. */
  var feature = parseInt(root.getAttribute("data-feature"), 10);
  if (isNaN(feature)) feature = -1;
  if (feature >= 0 && nodes[feature]) nodes[feature].classList.add("is-feature");

  function placePulse(index, progress) {
    var wire = wires[index];
    var pulse = pulses[index];
    if (!wire || !pulse) return;
    var pt = wire.getPointAtLength(lengths[index] * progress);
    pulse.setAttribute("cx", pt.x);
    pulse.setAttribute("cy", pt.y);
  }

  /* light one solution: its card, its wire, and its caption */
  function light(index) {
    nodes.forEach(function (node, n) { node.classList.toggle("is-lit", n === index || n === feature); });
    wires.forEach(function (wire, w) { wire.classList.toggle("is-lit", w === index || w === feature); });

    if (feature >= 0 || !textEl) return;     // a featured caption never swaps away
    caption.classList.add("is-swapping");
    setTimeout(function () {
      textEl.textContent = LABELS[index] || "";
      caption.classList.remove("is-swapping");
    }, 350);
  }

  /* run one pulse from its card down into the hub */
  function sendPulse(index) {
    var pulse = pulses[index];
    if (!pulse) return;
    var start = null;
    pulse.classList.add("is-live");

    raf = requestAnimationFrame(function frame(now) {
      if (!running) return;
      if (start === null) start = now;

      var p = (now - start) / TRAVEL;
      if (p >= 1) {
        placePulse(index, 1);
        pulse.classList.remove("is-live");
        return;
      }
      // ease-in-out: the packet gathers speed, then settles into the hub
      placePulse(index, p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2);
      raf = requestAnimationFrame(frame);
    });
  }

  function advance() {
    light(current);
    sendPulse(current);
    current = (current + 1) % LABELS.length;
  }

  function start() {
    if (running) return;
    running = true;
    advance();
    timer = setInterval(advance, STEP);
  }

  function stop() {
    running = false;
    clearInterval(timer);
    if (raf) cancelAnimationFrame(raf);
    timer = raf = null;
  }

  /* reduced motion: show the finished state — everything connected, nothing moves */
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
    nodes.forEach(function (n) { n.classList.add("is-lit"); });
    wires.forEach(function (w) { w.classList.add("is-lit"); });
    if (textEl && !textEl.textContent) textEl.textContent = "הכול מחובר למערכת אחת";
    return;
  }

  if (feature >= 0) current = feature;      // open the cycle on the featured solution
  else if (textEl) textEl.textContent = LABELS[0];

  // only animate while the hero is actually on screen
  if ("IntersectionObserver" in window) {
    new IntersectionObserver(function (entries) {
      if (entries[0].isIntersecting) start(); else stop();
    }, { threshold: 0 }).observe(root);
  } else {
    start();
  }
})();
