#!/usr/bin/env node
/* ==========================================================================
   FLOA — the generator.

   TWO THINGS, and the whole file is the line between them:

   src/ is the ENGINE. Components, layouts, the design system, the helpers. It
   has no brand, no domain, no phone number and no copy. It knows how to render
   a hero; it does not know whose.

   businesses/<key>/ is a BUSINESS. Its identity (brand, origin, colours,
   WhatsApp number, lead recipient), its copy, its page list and, if it wants
   one, a theme.css of its own. FLOA is simply the first of them.

   Each business is rendered into its own site: its own pages, its own
   stylesheet, its own script, its own sitemap. A business is never mixed into
   another one's output, so one of them can move to its own domain later by
   changing `origin` and nothing else.

     node build.mjs                build every business
     node build.mjs --only=floa    build one
     node build.mjs --watch        rebuild on any change under src/ or businesses/
     node build.mjs --serve        ... and serve it on http://localhost:5173
   ========================================================================== */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { createServer } from "node:http";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { watch } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");
const BUSINESSES = join(ROOT, "businesses");

const readSrc = (p) => readFile(join(SRC, p), "utf8");
const fingerprint = (s) => createHash("sha256").update(s).digest("hex").slice(0, 8);

async function write(outPath, contents) {
  const full = join(ROOT, outPath);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, contents, "utf8");
  return outPath;
}

/* A business folder may not be named after something the repo already owns:
   `out` is a real directory at the repo root, so a business called "css" would
   render its pages straight over the stylesheets. */
const RESERVED = new Set(["assets", "css", "js", "src", "businesses", "worker", "scripts", "node_modules"]);

/* --- asset bundling -------------------------------------------------------
   Every *.css / *.client.js under src/ is bundled. The order comes from
   src/bundle.js; anything unlisted is appended so it cannot be forgotten.
   The business's own theme.css, if it has one, comes last of all — see below. */
async function collect(dir, test, found = []) {
  for (const entry of await readdir(join(SRC, dir), { withFileTypes: true })) {
    const path = join(dir, entry.name).replaceAll("\\", "/");
    if (entry.isDirectory()) await collect(path, test, found);
    else if (test(entry.name)) found.push(path);
  }
  return found;
}

async function order(listed, test) {
  const all = await collect(".", test);
  const known = new Set(listed);
  const strays = all.map((p) => p.replace(/^\.\//, "")).filter((p) => !known.has(p));
  for (const stray of strays) console.warn(`  ! ${stray} is not in src/bundle.js — appended last`);
  return [...listed, ...strays];
}

const banner = (file, body) => `/* ${"=".repeat(70)}\n   ${file}\n   ${"=".repeat(70)} */\n${body}`;

async function concat(files, head, prelude = "", tail = []) {
  const parts = await Promise.all(files.map(async (f) => banner(f, await readSrc(f))));
  for (const { name, body } of tail) parts.push(banner(name, body));
  return `/* ${head}\n   Generated by build.mjs — edit the files under src/, not this one. */\n${prelude}\n${parts.join("\n")}`;
}

/* The business's theme: the LAST thing in the stylesheet, so it wins over every
   component above it. A business with no theme.css is not a special case — it
   simply takes the design system's defaults. */
async function theme(key) {
  try {
    return [{ name: `businesses/${key}/theme.css`, body: await readFile(join(BUSINESSES, key, "theme.css"), "utf8") }];
  } catch {
    return [];
  }
}

/* --- crawler-facing files ---------------------------------------------------
   Generated from the business's own siteMap, so they can never name a page the
   build doesn't produce, or miss one it does — and never name another
   business's page at all. */
function robotsTxt(origin) {
  return `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`;
}

function sitemapXml(entries) {
  const urls = entries.map((e) => `  <url>\n    <loc>${e.loc}</loc>\n  </url>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function llmsTxt(site, entries) {
  const links = entries.map((e) => `- [${e.title}](${e.loc}): ${e.description}`).join("\n");
  return `# ${site.brand}\n\n> ${site.tagline}. ${site.slogan}.\n\n## Pages\n\n${links}\n`;
}

/* --- the guard ------------------------------------------------------------
   The Worker validates a lead's page name against a whitelist of its own (it
   cannot import from here — it deploys on its own). So a page renamed here and
   not there is rejected by the endpoint with error "page", and the visitor is
   told only that we could not send. That failure is invisible until someone
   tries the form, which is exactly the kind of thing a build should catch. */
async function checkLeadPages(pageNames) {
  const worker = await readFile(join(ROOT, "worker/src/index.js"), "utf8");
  const block = worker.match(/const PAGES = \[([^\]]*)\]/s);
  if (!block) throw new Error("build: cannot find PAGES in worker/src/index.js");

  const allowed = [...block[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  const missing = pageNames.filter((n) => !allowed.includes(n));
  const stale = allowed.filter((n) => !pageNames.includes(n));

  if (missing.length || stale.length) {
    throw new Error(
      "build: worker/src/index.js PAGES is out of step with the site's pageName values.\n" +
      missing.map((n) => `  the site sends "${n}", the worker would reject it`).join("\n") +
      (missing.length && stale.length ? "\n" : "") +
      stale.map((n) => `  the worker still allows "${n}", which no page sends`).join("\n")
    );
  }
}

/* --- the build ------------------------------------------------------------ */
async function load() {
  const keys = (await readdir(BUSINESSES, { withFileTypes: true }))
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  return Promise.all(keys.map(async (key) => {
    const { business } = await import(pathToFileURL(join(BUSINESSES, key, "index.js")).href);
    if (business.key !== key) throw new Error(`build: businesses/${key} calls itself "${business.key}"`);
    if (business.out && RESERVED.has(business.out)) throw new Error(`build: "${business.out}" is a reserved directory`);
    return business;
  }));
}

/* One business, one site. Everything it emits lands under its own `out`, and
   every path inside it is relative to that — which is why the same folder can be
   served from floa.co.il/<key>/ today and from its own domain tomorrow. */
async function renderBusiness(business, bundle) {
  const { key, out, root, site, runtime, pages, siteMap } = business;

  const styles = await concat(
    await order(bundle.css, (n) => n.endsWith(".css")),
    `${site.brand} — one stylesheet, assembled from every component.`,
    "",
    await theme(key)
  );

  /* the browser gets its config from the same file the generator reads */
  const script = await concat(
    await order(bundle.js, (n) => n.endsWith(".client.js")),
    `${site.brand} — one script, assembled from every component behaviour.`,
    `\nwindow.FLOA = { config: ${JSON.stringify(runtime, null, 2)} };\n`
  );

  const assets = {
    css: `css/styles.css?v=${fingerprint(styles)}`,
    js: `js/main.js?v=${fingerprint(script)}`,
  };

  return Promise.all([
    write(join(out, "css/styles.css"), styles),
    write(join(out, "js/main.js"), script),
    write(join(out, "sitemap.xml"), sitemapXml(siteMap)),
    write(join(out, "llms.txt"), llmsTxt(site, siteMap)),
    /* robots.txt exists only at the root of a domain. A business served from a
       folder of someone else's domain does not get one, because nothing would
       ever fetch it. */
    ...(root ? [write("robots.txt", robotsTxt(site.origin))] : []),
    ...pages.map(async (page) => write(join(out, page.out), (await page.render(assets)).toString() + "\n")),
  ]);
}

async function build(only) {
  const started = Date.now();
  const bundle = await import(pathToFileURL(join(SRC, "bundle.js")).href);

  const all = await load();
  const chosen = only ? all.filter((b) => b.key === only) : all;
  if (!chosen.length) throw new Error(`build: no business named "${only}" under businesses/`);

  await checkLeadPages(chosen.flatMap((b) => b.leadPages ?? []));

  for (const business of chosen) {
    const written = await renderBusiness(business, bundle);
    console.log(`✓ ${business.key} — ${written.length} files`);
    for (const f of written) console.log(`  ${f.replaceAll("\\", "/")}`);
  }
  console.log(`  ${Date.now() - started}ms`);
}

/* --- dev ------------------------------------------------------------------ */
const TYPES = { ".html": "text/html", ".css": "text/css", ".js": "text/javascript", ".json": "application/json", ".svg": "image/svg+xml", ".webp": "image/webp", ".png": "image/png" };

function serve(port = 5173) {
  createServer(async (req, res) => {
    let path = decodeURIComponent(new URL(req.url, "http://x").pathname);
    if (path.endsWith("/")) path += "index.html";
    const file = resolve(ROOT, "." + path);
    if (!file.startsWith(ROOT)) return res.writeHead(403).end();
    try {
      const body = await readFile(file);
      res.writeHead(200, { "content-type": TYPES[extname(file)] ?? "application/octet-stream", "cache-control": "no-store" }).end(body);
    } catch {
      res.writeHead(404).end("not found");
    }
  }).listen(port, () => console.log(`  http://localhost:${port}\n`));
}

async function main() {
  const argv = process.argv.slice(2);
  const flag = (f) => argv.includes(f);
  const only = argv.find((a) => a.startsWith("--only="))?.slice("--only=".length);

  await build(only);

  if (flag("--serve")) serve();
  if (flag("--watch") || flag("--serve")) {
    let queued = null;
    const rebuild = (file) => {
      clearTimeout(queued);                                  // one rebuild per burst of saves
      queued = setTimeout(() => {
        console.log(`\n↻ ${file}`);
        /* A fresh process, not build() again: ESM caches every module it has
           already imported, so an in-process rebuild would keep re-rendering
           the content it read the first time. */
        spawnSync(process.execPath, [fileURLToPath(import.meta.url), ...argv.filter((a) => a !== "--serve" && a !== "--watch")], { stdio: "inherit" });
      }, 60);
    };
    watch(SRC, { recursive: true }, (_e, file) => rebuild(file));
    watch(BUSINESSES, { recursive: true }, (_e, file) => rebuild(file));
    console.log("  watching src/ and businesses/ …");
  }
}

main().catch((err) => { console.error(err); process.exit(1); });
