#!/usr/bin/env node
/* ==========================================================================
   FLOA — the generator.

   Pages are not files you edit. They are a list of components with props
   (src/pages/*), fed by content (src/content/*), rendered to static HTML here.
   Component CSS and JS are concatenated into one stylesheet and one script,
   fingerprinted, and linked from every page.

     node build.mjs            build once into the repo root
     node build.mjs --watch    rebuild on any change under src/
     node build.mjs --serve    ... and serve it on http://localhost:5173
   ========================================================================== */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { createServer } from "node:http";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { watch } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");

const read = (p) => readFile(join(SRC, p), "utf8");
const fingerprint = (s) => createHash("sha256").update(s).digest("hex").slice(0, 8);

async function write(outPath, contents) {
  const full = join(ROOT, outPath);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, contents, "utf8");
  return outPath;
}

/* --- asset bundling -------------------------------------------------------
   Every *.css / *.client.js under src/ is bundled. The order comes from
   src/bundle.js; anything unlisted is appended so it cannot be forgotten. */
async function collect(dir, test, found = []) {
  for (const entry of await readdir(join(SRC, dir), { withFileTypes: true })) {
    const path = join(dir, entry.name).replaceAll("\\", "/");
    if (entry.isDirectory()) await collect(path, test, found);
    else if (test(entry.name)) found.push(path);
  }
  return found;
}

async function order(listed, test) {
  const all = await collect(".", test);
  const known = new Set(listed);
  const strays = all.map((p) => p.replace(/^\.\//, "")).filter((p) => !known.has(p));
  for (const stray of strays) console.warn(`  ! ${stray} is not in src/bundle.js — appended last`);
  return [...listed, ...strays];
}

async function concat(files, banner, prelude = "") {
  const parts = await Promise.all(
    files.map(async (f) => `/* ${"=".repeat(70)}\n   ${f}\n   ${"=".repeat(70)} */\n${await read(f)}`)
  );
  return `/* ${banner}\n   Generated by build.mjs — edit the files under src/, not this one. */\n${prelude}\n${parts.join("\n")}`;
}

/* --- crawler-facing files ---------------------------------------------------
   Generated from siteMap (src/pages/index.js), which lists exactly the pages
   `pages` emits — so these can never name a page the build doesn't produce,
   or miss one it does. */
function robotsTxt(origin) {
  return `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`;
}

function sitemapXml(entries) {
  const urls = entries.map((e) => `  <url>\n    <loc>${e.loc}</loc>\n  </url>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function llmsTxt(site, entries) {
  const links = entries.map((e) => `- [${e.title}](${e.loc}): ${e.description}`).join("\n");
  return `# ${site.brand}\n\n> ${site.tagline}. ${site.slogan}.\n\n## Pages\n\n${links}\n`;
}

/* --- the guard ------------------------------------------------------------
   The Worker validates a lead's page name against a whitelist of its own (it
   cannot import from src/ — it deploys on its own). So a page renamed here and
   not there is rejected by the endpoint with error "page", and the visitor is
   told only that we could not send. That failure is invisible until someone
   tries the form, which is exactly the kind of thing a build should catch. */
async function checkLeadPages(pageNames) {
  const worker = await readFile(join(ROOT, "worker/src/index.js"), "utf8");
  const block = worker.match(/const PAGES = \[([^\]]*)\]/s);
  if (!block) throw new Error("build: cannot find PAGES in worker/src/index.js");

  const allowed = [...block[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  const missing = pageNames.filter((n) => !allowed.includes(n));
  const stale = allowed.filter((n) => !pageNames.includes(n));

  if (missing.length || stale.length) {
    throw new Error(
      "build: worker/src/index.js PAGES is out of step with the site's pageName values.\n" +
      missing.map((n) => `  the site sends "${n}", the worker would reject it`).join("\n") +
      (missing.length && stale.length ? "\n" : "") +
      stale.map((n) => `  the worker still allows "${n}", which no page sends`).join("\n")
    );
  }
}

/* --- the build ------------------------------------------------------------ */
const load = (mod) => import(pathToFileURL(join(SRC, mod)).href);

async function build() {
  const started = Date.now();
  const bundle = await load("bundle.js");
  const { pages, siteMap } = await load("pages/index.js");
  const { runtime, site } = await load("content/site.js");

  const { home } = await load("content/home.js");
  const { solutions } = await load("content/solutions.js");
  await checkLeadPages([home.pageName, ...solutions.map((s) => s.pageName)]);

  const styles = await concat(
    await order(bundle.css, (n) => n.endsWith(".css")),
    "FLOA — one stylesheet, assembled from every component."
  );

  /* the browser gets its config from the same file the generator reads */
  const script = await concat(
    await order(bundle.js, (n) => n.endsWith(".client.js")),
    "FLOA — one script, assembled from every component behaviour.",
    `\nwindow.FLOA = { config: ${JSON.stringify(runtime, null, 2)} };\n`
  );

  const assets = {
    css: `css/styles.css?v=${fingerprint(styles)}`,
    js: `js/main.js?v=${fingerprint(script)}`,
  };

  const written = await Promise.all([
    write("css/styles.css", styles),
    write("js/main.js", script),
    write("robots.txt", robotsTxt(site.origin)),
    write("sitemap.xml", sitemapXml(siteMap)),
    write("llms.txt", llmsTxt(site, siteMap)),
    ...pages.map(async (page) => write(page.out, (await page.render(assets)).toString() + "\n")),
  ]);

  console.log(`✓ ${written.length} files in ${Date.now() - started}ms`);
  for (const f of written) console.log(`  ${f}`);
}

/* --- dev ------------------------------------------------------------------ */
const TYPES = { ".html": "text/html", ".css": "text/css", ".js": "text/javascript", ".json": "application/json", ".svg": "image/svg+xml", ".webp": "image/webp", ".png": "image/png" };

function serve(port = 5173) {
  createServer(async (req, res) => {
    let path = decodeURIComponent(new URL(req.url, "http://x").pathname);
    if (path.endsWith("/")) path += "index.html";
    const file = resolve(ROOT, "." + path);
    if (!file.startsWith(ROOT)) return res.writeHead(403).end();
    try {
      const body = await readFile(file);
      res.writeHead(200, { "content-type": TYPES[extname(file)] ?? "application/octet-stream", "cache-control": "no-store" }).end(body);
    } catch {
      res.writeHead(404).end("not found");
    }
  }).listen(port, () => console.log(`  http://localhost:${port}\n`));
}

async function main() {
  const flag = (f) => process.argv.includes(f);
  await build();

  if (flag("--serve")) serve();
  if (flag("--watch") || flag("--serve")) {
    let queued = null;
    watch(SRC, { recursive: true }, (_e, file) => {
      clearTimeout(queued);                                  // one rebuild per burst of saves
      queued = setTimeout(() => {
        console.log(`\n↻ ${file}`);
        /* A fresh process, not build() again: ESM caches every module it has
           already imported, so an in-process rebuild would keep re-rendering
           the content it read the first time. */
        spawnSync(process.execPath, [fileURLToPath(import.meta.url)], { stdio: "inherit" });
      }, 60);
    });
    console.log("  watching src/ …");
  }
}

main().catch((err) => { console.error(err); process.exit(1); });
