/* ==========================================================================
   GENERATED by build.mjs from businesses/<key>/index.js. Do not edit.

   Every business the lead endpoint serves: the brand its email is signed with,
   the NAME of the env var holding its recipient (never the address), the origins
   allowed to post on its behalf, and the pages that may send.
   ========================================================================== */
export const BUSINESSES = {
  "floa": {
    "brand": "FLOA",
    "to": "LEAD_TO",
    "origins": [
      "https://floa.co.il",
      "https://www.floa.co.il",
      "http://localhost:5173"
    ],
    "pages": [
      "דף הבית",
      "אתרים, אפליקציות ודפי נחיתה",
      "מערכות, אוטומציות וניהול העסק",
      "דף נחיתה החל מ־500 ₪"
    ]
  },
  "prolink": {
    "brand": "ProLink",
    "to": "LEAD_TO_PROLINK",
    "origins": [
      "https://floa.co.il",
      "https://www.floa.co.il",
      "http://localhost:5173"
    ],
    "pages": [
      "פרולינק"
    ]
  }
};
