/* ==========================================================================
   The lead endpoint — for every business, not just FLOA.

   The sites are static (GitHub Pages) and have no server of their own, so this
   Worker IS the server. It exists for one reason: to hold the Resend API key
   somewhere the browser can never see it, and to email a lead to an inbox.

   POST /lead  { business, name, phone, page, url, company, utm_* } -> { ok: true }
   Every page sends the same two fields, a name and a phone. `business` says whose
   lead it is, and that is the only thing that decides where it lands: a client's
   lead goes to the client's inbox and never to ours. The utm_* fields are
   optional and ride along only when the visitor arrived from a campaign.

   Nothing is stored. Not here, not in Firebase, not anywhere — the lead becomes
   an email and that is the whole of its life.

   BUSINESSES is generated by build.mjs from businesses/<key>/index.js, so the
   brands, origins and page names here can never drift from the ones the sites
   actually render. Each business names the env var holding its recipient; the
   address itself is never in the repo.

   Secrets and vars (see worker/README.md):
     RESEND_API_KEY   the Resend key
     LEAD_FROM        the verified sender          (FLOA <no-reply@floa.co.il>)
     LEAD_TO          FLOA's own inbox — and one var per client, as named by
                      its `to` in the table
   ========================================================================== */
import { BUSINESSES } from "./businesses.js";

/* A lead sent before the sites were rebuilt carries no `business` field. It can
   only have come from FLOA, because FLOA is the only business that existed then. */
const DEFAULT_BUSINESS = "floa";

const ALLOWED_ORIGINS = [...new Set(Object.values(BUSINESSES).flatMap((b) => b.origins))];

/* UTM parameters, carried from the ad click through to the lead's inbox so a
   campaign's source is never lost between the click and the form */
const UTM_FIELDS = [
  ["utm_source", "מקור"],
  ["utm_medium", "מדיום"],
  ["utm_campaign", "קמפיין"],
  ["utm_term", "מונח"],
  ["utm_content", "תוכן"],
];

const cors = (origin) => ({
  "access-control-allow-origin": ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0],
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers": "content-type",
  "access-control-max-age": "86400",
});

const json = (body, status, origin) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", ...cors(origin) },
  });

/* --- validation: the server decides, not the browser ----------------------- */

/* an Israeli mobile or landline, however it was typed */
function normalizePhone(value) {
  const digits = String(value || "").replace(/[^\d+]/g, "").replace(/^\+972/, "0").replace(/^972/, "0");
  return /^0(?:5\d{8}|[2-489]\d{7})$/.test(digits) ? digits : null;
}

/* 0500000000 -> 050-0000000. The email is read by a human who is about to dial,
   so it shows the number the way a person writes it; the tel: link uses the raw
   digits. */
const prettyPhone = (digits) =>
  digits.startsWith("05")
    ? `${digits.slice(0, 3)}-${digits.slice(3)}`
    : `${digits.slice(0, 2)}-${digits.slice(2)}`;

/* a free-text field, trimmed and capped so a lead can never blow up the email
   it becomes; empty is fine, these are all optional */
const freeText = (value, max = 300) => String(value || "").trim().slice(0, max);

function validate(body, origin) {
  /* whose lead this is. Everything below is judged against THIS business: its
     pages, its origins, its inbox. */
  const business = BUSINESSES[String(body.business || DEFAULT_BUSINESS)];
  if (!business) return { error: "business" };

  /* the posting page must be one this business is actually served from, so a
     site cannot send a lead in another business's name */
  if (!business.origins.includes(origin)) return { error: "origin" };

  const name = String(body.name || "").trim();
  const phone = normalizePhone(body.phone);
  const page = String(body.page || "").trim();

  if (name.length < 2 || name.length > 80) return { error: "name" };
  if (!phone) return { error: "phone" };
  if (!business.pages.includes(page)) return { error: "page" };

  /* the visitor's page URL is shown in the email, so it must be one of ours */
  let url = "";
  try {
    const u = new URL(String(body.url || ""));
    if (business.origins.includes(u.origin)) url = u.href;
  } catch { /* an unparseable URL is simply not shown */ }

  const extra = {};
  for (const [key] of UTM_FIELDS) {
    const value = freeText(body[key]);
    if (value) extra[key] = value;
  }

  return { business, lead: { name, phone, page, url, ...extra } };
}

/* HTML-escape: the name is visitor input and it lands inside an email body */
const esc = (s) => String(s).replace(/[&<>"']/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

/* Israel time, dd.mm.yyyy, HH:MM — the inbox is read in Israel */
function stamp() {
  const parts = new Intl.DateTimeFormat("he-IL", {
    timeZone: "Asia/Jerusalem",
    day: "2-digit", month: "2-digit", year: "numeric",
    hour: "2-digit", minute: "2-digit", hour12: false,
  }).formatToParts(new Date());
  const at = (t) => parts.find((p) => p.type === t).value;
  return `${at("day")}.${at("month")}.${at("year")}, ${at("hour")}:${at("minute")}`;
}

/* The email a lead becomes.

   RTL the hard way, on purpose: Gmail throws away <html> and <body> and keeps
   only what is inside, so a dir="rtl" up there is gone by the time the mail is
   read — which is why this one used to arrive left-aligned. Every element that
   holds text therefore carries its own dir="rtl" and its own text-align:right,
   inline. It costs a few attributes and it survives the mail client.

   The heading already says the mail is a new lead, so nothing under it repeats
   that. Straight from the heading into the details. */
function email(lead, brand) {
  const when = stamp();

  /* 0587078708 -> 972587078708, the only form wa.me accepts */
  const waNumber = `972${lead.phone.slice(1)}`;

  /* Every row is [label, value, href?]: the value itself is the link, so nothing
     in this mail is a bare URL on its own line. The page name opens the page, the
     phone number dials it. The phone row also carries a second link, WhatsApp,
     because reaching a new lead by message is as likely as by call. */
  const rows = [
    ["עמוד", lead.page, lead.url],
    ["שם", lead.name],
    ["טלפון", prettyPhone(lead.phone), `tel:${lead.phone}`, `https://wa.me/${waNumber}`],
    ["תאריך ושעה", when],
    ...UTM_FIELDS.map(([key, label]) => [label, lead[key]]),
  ].filter(([, v]) => v);

  /* the plain-text copy has no links, so there the URL still earns its place */
  const text = rows.map(([k, v, href]) => `${k}: ${v}${href && !href.startsWith("tel:") ? ` (${href})` : ""}`).join("\n");

  const html = `<!doctype html>
<html lang="he" dir="rtl">
  <body dir="rtl" style="margin:0;padding:24px;background:#E9F0EE;font-family:Arial,Helvetica,sans-serif;color:#0F2A33;direction:rtl;text-align:right">
    <table role="presentation" dir="rtl" align="center" width="100%" style="max-width:560px;margin:0 auto;background:#fff;border:1px solid #DCE6E3;border-radius:16px;padding:28px;direction:rtl">
      <tr><td dir="rtl" style="direction:rtl;text-align:right">
        <h1 style="margin:0 0 20px;font-size:20px;color:#0A6C61;text-align:right">פנייה חדשה מאתר ${esc(brand)}</h1>
        <table role="presentation" dir="rtl" width="100%" style="font-size:15px;border-collapse:collapse;direction:rtl">
          ${rows.map(([k, v, href, wa]) => `
          <tr>
            <td align="right" style="padding:8px 0;color:#586C73;width:120px;vertical-align:top;text-align:right">${esc(k)}</td>
            <td align="right" style="padding:8px 0;font-weight:bold;text-align:right">${href
              ? `<a href="${esc(href)}" style="color:#0A6C61">${esc(v)}</a>`
              : esc(v)}${wa
              ? `<a href="${esc(wa)}" style="display:inline-block;margin-right:10px;padding:4px 12px;border-radius:999px;background:#0E8C7E;color:#fff;text-decoration:none;font-size:13px;font-weight:bold">WhatsApp</a>`
              : ""}</td>
          </tr>`).join("")}
        </table>
      </td></tr>
    </table>
  </body>
</html>`;

  return {
    subject: `פנייה חדשה מאתר ${brand}: ${lead.page}`,
    text,
    html,
  };
}

/* --- rate limiting --------------------------------------------------------
   A best-effort brake on repeat sends, keyed by IP, held in the Worker's cache.
   It is not a hard guarantee (the cache is per-colo), but it stops the obvious
   abuse — a script hammering the endpoint from one address. The honeypot below
   catches the rest. */
async function rateLimited(ip) {
  const key = new Request(`https://ratelimit.floa.internal/${encodeURIComponent(ip)}`);
  const cache = caches.default;
  if (await cache.match(key)) return true;
  await cache.put(key, new Response("1", { headers: { "cache-control": "max-age=30" } }));
  return false;
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("origin") || "";

    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors(origin) });
    if (request.method !== "POST") return json({ ok: false, error: "method" }, 405, origin);
    if (!ALLOWED_ORIGINS.includes(origin)) return json({ ok: false, error: "origin" }, 403, origin);

    const url = new URL(request.url);
    if (url.pathname !== "/lead") return json({ ok: false, error: "not found" }, 404, origin);

    let body;
    try {
      body = await request.json();
    } catch {
      return json({ ok: false, error: "body" }, 400, origin);
    }

    /* the honeypot. A human never sees the field, so a filled one is a bot —
       answer 200 so the bot believes it succeeded and does not retry. */
    if (String(body.company || "").trim()) return json({ ok: true }, 200, origin);

    const ip = request.headers.get("cf-connecting-ip") || "unknown";
    if (await rateLimited(ip)) return json({ ok: false, error: "rate" }, 429, origin);

    const { business, lead, error } = validate(body, origin);
    if (error) return json({ ok: false, error }, 400, origin);

    /* The business's inbox, from the env var IT names. A business whose var was
       never set must fail loudly here: the alternative is a lead quietly landing
       in someone else's inbox, and there is no recovering from that. */
    const to = env[business.to];
    if (!to) {
      console.error(`lead dropped: ${business.to} is not set on the Worker`);
      return json({ ok: false, error: "send" }, 502, origin);
    }

    const { subject, text, html } = email(lead, business.brand);

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.RESEND_API_KEY}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        /* Always FLOA's verified sender: floa.co.il is the domain with SPF and
           DKIM in Resend, and it is the only one it will send as. The mail is
           ABOUT the client's business (subject, heading) but it is delivered by
           ours, which is also what makes a client need no mail setup at all. */
        from: env.LEAD_FROM,
        to: [to],
        reply_to: to,
        subject,
        text,
        html,
      }),
    });

    /* The visitor is told "thank you" ONLY if the mail provider accepted it. If
       Resend refused, the browser gets a failure and keeps the typed fields. */
    if (!res.ok) {
      console.error("resend rejected the lead", res.status, await res.text());
      return json({ ok: false, error: "send" }, 502, origin);
    }

    return json({ ok: true }, 200, origin);
  },
};
