/* ==========================================================================
   What every CV of this business shares.

   There is more than one CV now: the same career, told for a different job. The
   contact details, the photograph and the share title are the same man in all
   of them, so they are written once here. Only the copy differs, and the copy
   lives in a file per document (cv-architect.js, cv-analyst.js).

   ADDRESSES

   The business folder is `cv/`, so a document is one slug inside it:

     dist/cv/<slug>/index.html         ->  floa.co.il/cv/<slug>/
     dist/cv/<slug>/he/index.html      ->  floa.co.il/cv/<slug>/he/

   Nothing is written for /cv/ itself, so it 404s: there is no index of Ofir's
   résumés, only the one whose address was handed to someone.

   `address()` works all of that out from the slug and the language, which is
   what keeps two documents from drifting into two sets of relative paths. A
   third CV declares a slug and inherits every link in it.
   ========================================================================== */

export const CONTACT = {
  phoneHref: "tel:+972587078708",
  mailHref: "mailto:ofir.aviram@gmail.com",
  linkedinHref: "https://www.linkedin.com/in/aviramo",
  mail: "ofir.aviram@gmail.com",
  linkedin: "linkedin.com/in/aviramo",
};

export const DEMO = "https://once-lake.vercel.app/";

/* The name a link to any of these documents shows in a message or a feed. Both
   scripts, because the same link is shared into Hebrew threads and English ones
   and a card that guesses wrong is a card nobody recognises. */
export const SHARE_TITLE = "אופיר אבירם | Ofir Aviram";

/* The photograph, square because it is a portrait, and JPEG because a social
   crawler is not a browser: several of them still do not decode the WebP the
   site itself serves. Built by scripts/gen_cv_share.py from the same source
   image FLOA uses, so there is one photograph and not two. */
export const SHARE_IMAGE = {
  src: "assets/ofir-aviram.jpg",
  width: 1200,
  height: 1200,
  alt: "Ofir Aviram",
};

/* Every path a document has, from its slug and its language. `base` is how the
   page reaches this business's stylesheet, and it is simply its depth below the
   business folder: one level for the Latin page, two for the Hebrew one under
   it. Every href returned is relative to the business folder, which is what
   ctx.url() expects (see src/lib/context.js). */
export const address = (slug, lang) => {
  const en = `${slug}/`;
  const he = `${slug}/he/`;
  const self = lang === "he" ? he : en;

  return {
    out: `${self}index.html`,
    path: `cv/${self}`,
    base: lang === "he" ? "../../" : "../",
    homeHref: lang === "he" ? "../../" : "../",
    alternates: [{ lang: "en", href: en }, { lang: "he", href: he }],
    altLang: lang === "he"
      ? { href: en, label: "English", lang: "en" }
      : { href: he, label: "עברית", lang: "he" },
  };
};

/* The printed copy of a document, generated by scripts/gen_cv_pdf.mjs into
   public/<slug>/ and copied into the site by the build. A document with no PDF
   yet simply does not call this, and the page renders without the button. */
export const pdf = (slug, lang) => (lang === "he"
  ? { href: `${slug}/ofir-aviram-cv-he.pdf`, name: "אופיר אבירם - קורות חיים.pdf", label: "הורדת PDF" }
  : { href: `${slug}/ofir-aviram-cv.pdf`, name: "Ofir Aviram - CV.pdf", label: "Download PDF" });
